//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOBODEGA
    {
        public int PRODUCTO_IDProducto { get; set; }
        public int BODEGA_IDBodega { get; set; }
        public int Cajas { get; set; }
        public int Sueltas { get; set; }
    
        public virtual BODEGA BODEGA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
